### ISSUE TITLE
Ajouter la possibilité de réaliser des actions supplémentaires sur une DB

### ISSUE THREAD

**Issue by amandine-sahl** [PnEcrins/UsersHub#1]
Idée : être en mesure de rajouter des opérations (Instructions SQL) qui seraient lancées à la fin d'une opération de mise à jour en fonction de l'action réalisée sur la base de données

**Comment by camillemonchicourt** [comment]
@amandine-sahl ticket à fermer ?

**Comment by camillemonchicourt** [comment]
Yes
