### ISSUE TITLE
Passer en sha256

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/UsersHub#14]
Voir https://github.com/PnX-SI/UsersHub-authentification-module/commit/9e880d1177f30ad193c7c695e90fe4065d8d8cb4

Cela nécessite de reporter cette modification dans toutes les applications qui utilisent UsersHub.

**Comment by amandine-sahl** [comment]
Non la correction correspond à l'inverse en réalité, il n'y a pas de répercussion à avoir. Le setter encodait à tord le mot de passe en sha256.

**Comment by camillemonchicourt** [comment]
Oui j'ai bien capté. Justement comme évoqué par @ksamuel, il faudrait basculer l'encodage en sha256 et non plus md5. 
Et cela impliquerait de modifier partout.
