### ISSUE TITLE
Meilleur encodage des MDP

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/UsersHub#17]
Voir https://github.com/PnX-SI/UsersHub-authentification-module/pull/4
On utilise actuellement du md5, il serait préférable de passer en sha256. 
A voir si cela impliquerait des modifications seulement dans UsersHub-authentification-module ou aussi dans les applis.
Ce qui est sur c'est que ça entraînerait des modifications dans les applications qui n'utilisent pas UsersHub-authentification-module (Geotrek ?; Police....)

**Comment by camillemonchicourt** [comment]
Pour ne pas avoir à revoir toutes les applications existantes basées sur UsersHub mais disposer d'une authentification plus robuste pour les nouvelles applis, je propose de rajouter un deuxième champs avec le mot de passe mais encodé celui-ci en sha256. Par exemple `passplus`. 

Les applications pourraient utiliser l'un ou l'autre.

**Comment by gildeluermoz** [comment]
Ok pour le champ ``passplus`` ou ``passsha``.
Le SHA256 ou SHA512 "nécessite" un sel cryptographique : une phrase par exemple.
Pour une sécurité accrue, il ne faut pas stocker ce sel dans la base mais dans un fichier de conf de l'appli.
Le décryptage du hash ne pourra se faire qu'avec le sel utilisé à l'encodage (à ne pas perdre et à trimbaler dans toutes les applis utilisant ce système de cryptage).

Modif de UsersHub à prévoir.

**Comment by gildeluermoz** [comment]
Done
