### ISSUE TITLE
utilisateurs.cor_app_privileges VS utilisateurs.cor_role_tag ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/UsersHub#31]
``utilisateurs.cor_app_privileges`` semble très orientée sur le fonctionnement de GeoNature (un rôle a un tag de type ``action``, associé à un tag de type ``object`` (portée), associé à une ``application`` (module) mais du coup elle est spécifique ?

Par ailleurs on associe des tags à des role dans ``utilisateurs.cor_role_tag``.

**Comment by gildeluermoz** [comment]
Oui, il y a un soucis. Il faut qu'on creuse ça ensemble. 
A minima, il me semble que l'on doit définir un nouveau type `portée`. 
Dans l'idée une action avec une portée permet de créer le CRUVED (plus ou moins générique).
Il faut que l'on modifie le modèle pour associer librement id_role et id_application avec un ou pls tags.

**Comment by camillemonchicourt** [comment]
OK, oui j'avais noté des évolutions au niveau des types de tags (https://github.com/PnEcrins/UsersHub/issues/30), mais peut-être que le mieux serait carrément de créer un autre type.
On a aussi commencé à voir comment utiliser les tags pour créer des vues qui simuleraient les tables de UsersHub V1 : https://github.com/PnEcrins/UsersHub/commit/0b7783b1bb4c0f12738f950aa355b4f26c5fdbf4

**Comment by camillemonchicourt** [comment]
Un type de tag ``Scope`` a été ajouté.
Et une table ``utilisateurs.cor_role_tag_application`` a été crée.
