### ISSUE TITLE
SQL - Supprimer les exceptions

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/UsersHub#44]
Dans https://github.com/PnEcrins/UsersHub/blob/separate-sql/data/usershub-db.sql

Je ne sais pas à quoi elles correspondent mais elles renvoient des erreurs.

**Comment by camillemonchicourt** [comment]
Fait : https://github.com/PnEcrins/UsersHub/commit/e2b7830d35698c2fa1a8b5069be84f17371a238e
OK ? 
A faire dans Update ?

**Comment by gildeluermoz** [comment]
Dans le update, ces exceptions ont une vraie raison d'être car si les enregistrements existe, le script peut se poursuivre.

**Comment by camillemonchicourt** [comment]
OK du coup ils avaient peut-être aussi un intérêt dans le script de création du schéma et de ses tables ?

**Comment by gildeluermoz** [comment]
C'était à la demande de Kevin Samuel de pouvoir relancer un script de création sur une base existante.
Dans le cadre d'une création du schéma ou de la base, je ne vois pas trop l'intérêt, on ne le fait pas ailleurs et c'est lourd. Donc, non on ne le garde pas dans le script de création.

**Comment by camillemonchicourt** [comment]
OK
