### ISSUE TITLE
Code application

### ISSUE THREAD

**Issue by amandine-sahl** [PnEcrins/UsersHub#54]
Pour des questions de volatilité de serait bien d'avoir un code application qui soit unique et non modifiable de façon à pouvoir récupérer l'id application qui lui est potentiellement différent d'une application à l'autre.

**Comment by camillemonchicourt** [comment]
Ah oui en effet ça serait très utile pour GeoNature et ses modules notamment.

**Comment by gildeluermoz** [comment]
tu veux dire s'appuyer sur un uuid ?

**Comment by camillemonchicourt** [comment]
Non un code pérenne et partagé. 
Genre GN pour GeoNature.
TH pour TaxHub.
UH pour UsersHub
GNOT pour Occtax
GNADM pour l'administration GeoNature 
Etc etc..

**Comment by gildeluermoz** [comment]
Ok ! Ok! Bonne idée.
Y'a plus qu'à !

**Comment by camillemonchicourt** [comment]
Fait dans la refonte en cours de la BDD : https://github.com/PnEcrins/UsersHub/commit/5f946375213e18269435cd5e2279b57e8ddba72e

**Comment by camillemonchicourt** [comment]
A ajouter dans le formulaire Applications et à afficher dans la liste des Applications.
