### ISSUE TITLE
Pouvoir définir un port spécifique pour la BDD.

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/UsersHub#6]
Ajout d'un paramètre dans ``connecter.php`` et l'utiliser dans les fichier ``/web/update_xxxx/php``.

**Comment by ClaireLagaye** [comment]
Modifications faite dans la pull request

**Comment by camillemonchicourt** [comment]
Fait dans la version 1.1.0 - https://github.com/PnEcrins/UsersHub/releases/tag/v1.1.0
