### ISSUE TITLE
Paramètre fill_md5_pass ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/UsersHub#62]
Ajouter un paramètre ``fill_md5_pass`` pour que le mot de passe md5 puisse ne pas être renseigné. 
En effet, ceux qui n'ont pas de vieilles applications n'ont pas besoin de ce MDP et ce serait dommage de leur coller ce champs fragile si il n'est pas utilisé.

**Comment by gildeluermoz** [comment]
Existe t-il des cas où le pass_md5 serait utile si la `PASS_METHOD = 'hash'` ?
Sinon, on supprime le paramètre `FILL_MD5_PASS` et on utilise `PASS_METHOD` pour savoir s'il faut remplir le champ `pass_md5`

**Comment by camillemonchicourt** [comment]
Je sais pas si c'est suffisant car ``PASS_METHOD`` renseigne sur la méthode d'authentification d'une application. En l'occurrence, ici il indique la méthode d'authentification pour se connecter à UsersHub. 
Mais cela ne veut pas dire que d'autres applications anciennes connecté à ce même UsersHub ne fonctionnent pas uniquement en MD5, non ?
J'ai l'impression que c'est pas la même chose.

**Comment by gildeluermoz** [comment]
Ok, effectivement. Donc on laisse comme ça, tout est bon.
