### ISSUE TITLE
2.0.2 Information sur la configuration du site Web

### ISSUE THREAD

**Issue by CistudeNature** [PnEcrins/UsersHub#73]

**Comment by CistudeNature** [comment]
Je viens juste d'installer la version 2.0.2 de UsersHub. La procédure d'installation s'est déroulée sans incidents. Les services apache2 et supervisor ont démarrés correctement (pas d'erreurs dans les fichiers log). Cependant, je n'arrive pas à accéder à UsersHub ( http://mon-domaine.fr/usershub).
Pourriez-vous m'indiquer : le répertoire racine du site UsersHub et le composant (accueil.php, login.html,..) qui permet d'accéder à la page d'identification de UsersHub2?
Merci d'avance pour votre retour.

**Comment by camillemonchicourt** [comment]
Si vous avez installez UsersHub avec le script d'installation globale de GeoNature (le plus simple - https://geonature.readthedocs.io/fr/latest/installation-all.html), alors l'application est accessible à l'URL http://mondomaine/usershub

Si vous avez installe UsersHub à part, il faut voir votre configuration Apache : https://usershub.readthedocs.io/fr/latest/installation.html#configuration-apache

L'application n'est pas développée en PHP mais en Python et les templates sont générés dynamiquement par le serveur, à partir des templates HTML : https://github.com/PnEcrins/UsersHub/tree/master/app/templates
