### ISSUE TITLE
oubli dans la doc pour la modif de la conf apache

### ISSUE THREAD

**Issue by RomainBaghi** [PnEcrins/UsersHub#76]
Je pense qu'il faut remplacer la ligne suivante :
sudo nano /etc/apache2/sites-available/usershub
par
sudo nano /etc/apache2/sites-available/usershub.conf

**Comment by TheoLechemia** [comment]
A quelle doc est-ce que tu fais référence ?
Ici, elle parait OK: https://github.com/PnEcrins/UsersHub/blob/master/docs/migration-v1v2.rst

**Comment by RomainBaghi** [comment]
Pardon, je parlais de cette page : https://github.com/PnX-SI/GeoNature/blob/master/docs/update-all-RC3-to-RC4.rst

**Comment by TheoLechemia** [comment]
Corrigé

**Comment by camillemonchicourt** [comment]
Oui ceci est un tutoriel informatif,  pas une doc officielle.
